FROM node:20.18.0 as builder

WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.24.0-alpine
#COPY --from=builder /app/dist /usr/share/nginx/html
COPY --from=builder /app/build /app
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80